on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        required: true
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Publish To Npm
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
        run: npm publish --access=public

      - name: Sync To Cnpm
        run: npx cnpm sync ${{inputs.name}}
