name: Publish Npm Package
on:
  pull_request:
    branches: [master]
    types:
      - closed
jobs:
  node-npm:
    needs: checkout
    uses: kne-union/actions/.github/workflows/publish-node-workflow.yml@master
    secrets: inherit
    with:
      package_name: '@kne-template/node'
